site_name: Data Platform Lab
site_description: Building a production-grade Data Platform from first principles
site_url: https://swapnilsankla.github.io/data-platform-lab/
repo_url: https://github.com/SwapnilSankla/data-platform-lab
repo_name: SwapnilSankla/data-platform-lab
use_directory_urls: true

theme:
  name: material

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - toc.follow
    - content.action.edit
    - content.action.view

  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Light mode    

nav:
  - Home: index.md
  - Spark:
      - Execution Model:
          - Internal Execution Model: spark/internal-execution-model.md
          - Lazy Evaluation: spark/lazy-evaluation.md
          - Transformations vs Actions: spark/transformations-vs-actions.md

      - Physical Execution:
          - Execution Partitions: spark/execution-partitions.md
          - Physical Plan: spark/how-to-interpret-spark-physical-plan.md

      - Data Movement:
          - Narrow vs Wide Transformations: spark/narrow-vs-wide-transformations.md
          - Shuffle: spark/shuffle.md
          - Repartition vs Coalesce: spark/repartition-vs-coalesce.md

      - Query Patterns:
          - Sort Merge Join: spark/joins/sort-merge-join.md

      - Performance:
          - Caching and Persistence: spark/caching-and-persistence.md

  - Lakehouse:
      - Evolution: lakehouse/01-evolution-of-modern-data-storage.md
      - Storage Model: lakehouse/02-row-vs-column-storage.md
      - Parquet Anatomy: lakehouse/03-anatomy-of-a-parquet-file.md
      - Row Groups: lakehouse/04-row-groups-the-unit-of-parallelism-in-a-parquet-file.md
      - Concepts:
          - Object Storage vs Lake vs Lakehouse: lakehouse/object-storage-vs-lake-vs-lakehouse.md
  - ClickHouse:
      - Why ClickHouse Rewrites Data: clickhouse/01-why-clickhouse-rewrites-data.md
      - The Hidden Cost Of The Inserts: clickhouse/02-the-hidden-cost-of-the-inserts.md
      - Why Small Parts Destroy Systems: clickhouse/03-why-small-parts-destroy-systems.md
      - Merge Amplification (The Invisible Multiplier): clickhouse/04-merge-amplification.md
      - Merge Selection & Starvation: clickhouse/05-merge-selection-and-starvation.md
      - Order By - A Physical Design Tool: clickhouse/06-order-by-a-physical-design-tool.md
      - Granules, Primary Index, and the Illusion of Skipping: clickhouse/07-granules-primay-index-illusion-of-skipping.md
      - IO Vs CPU - Finding The Real Bottleneck: clickhouse/08-io-vs-cpu-finding-the-real-bottleneck.md
      - When Optimization Stopes Working: clickhouse/09-when-optimization-stops-working.md
      - Pre-aggregation, Multi-tenancy and System Boundaries: clickhouse/10-pre-aggregation-multi-tenancy-and-system-boundaries.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

extra:
  generator: false

extra_css:
  - stylesheets/extra.css      